pipeline
{
    agent any

    environment
    {
        IMAGE_TAG="${BUILD_NUMBER}"
    }

    stages{
        stage('Clone repository') {
        git https://github.com/clouddevaws1961/Jenkins.git
        checkout scm
    }
    stage ('build')
            agent none
            steps {
                docker build -t sandy1961/sandydockerimage_1961:1
                docker push
                
            }
    }
}